export const  FETCH_SUBSCRIBER_BEGIN = "FETCH_SUBSCRIBER_BEGIN";
export const FETCH_SUBSCRIBER_SUCCESS = 'FETCH_SUBSCRIBER_SUCCESS';
export const FETCH_SUBSCRIBER_FAILURE = 'FETCH_SUBSCRIBER_FAILURE'
